---
# tasks file for default_packages

- name: Обновление пакетов программ
  shell: apt update -y

- name: Установка программ #Имя задачи
  apt: #Используемый модуль
    name: "{{ item }}" #Имя пакета из цикла
    state: present
  loop:
    - "{{ packages_to_install }}"

- name: Удаление apache2
  apt: #Используемый модуль
    name: apache2
    state: absent
  loop:
    - "{{ packages_to_install }}"
