---
- name: Изменение имени машины на имя из Inventory
  hosts: all
  roles:
    - role: change_hostname
  tags:
    - change_hostname

- name: Установка стандартных пакетов + для mediawiki
  hosts: mediawiki
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка и настройка балансирующего nginx + на серверах mediawiki
  hosts: nginx # Будет работать на узлах в группе nginx
  roles:
    - role: nginx_setup
  tags:
    - nginx_setup

- name: Отправка на машины закрытого ключа для работы scp
  hosts: all
  roles:
    - role: send_key
  tags:
    - send_key
